from utils.logging_utils import setup_logging, TextHandler
from utils.image_utils import resize_image_if_needed, overlay_text_on_image
from utils.tesseract_utils import check_tesseract, show_tesseract_install_guide